name: tic_tac_toe_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_bloc: ^8.1.3
  tic_tac_toe_lib:
    path: dependency/tic_tac_toe_lib
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand.ttf
          style: italic
  uses-material-design: true